version: "3"
services:
  api:
    container_name: waffle-api
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
  db:
    container_name: waffle-db
    image: mongo
    volumes:
      - ./mongo/data:/data/db
    ports:
      - "27017:27017"